### Ping
GET http://



### Echo
POST http://
Content-Type: application/json
{
    "mensagem": "Ola Mundo!!"
}


### Soma
GET http://


```http
### Subtracao
GET http://
```

```http
### Multiplicacao
GET http://?a=2&b=3
```

```http
### Divisao
POST http://
Content-Type: application/json

{
    "a": 10,
    "b": 2
}
```